provision/Provision-All.ps1, provision/Provision-EventHub.ps1, provision/Provision-StorageAccount.ps1, provision/Provision-StreamAnalyticsJob.ps1, provision/StreamAnalyticsJobDefinition.json
connects to #6 
connects to #32 
connects to #33 
@bennage @francischeung Please review and merge
=> add provisioning powershell and Stream Analytics jobdefinition.json

advisory-board.md
@francischeung can you take a quick look at this?
connects to mspnp/iot-journey-private#8
=> draft of advisory board faq

src/Implementation/Shared/Devices.Events/UpdateTemperatureEvent.cs, src/Implementation/Simulator/ScenarioSimulator/Device.cs, src/Implementation/Simulator/ScenarioSimulator/EventFactory.cs, src/Implementation/Simulator/ScenarioSimulator/SimulationScenarios.cs
=> correcting a misspelling

src/Implementation/Simulator/ScenarioSimulator.Tests/WhenSendingEvents.cs, src/Implementation/Simulator/ScenarioSimulator/EventSender.cs
=> Pulled out version form type.

docs/journal/00-introducing-the-journey.md
Fixed some small typos in the 'The Initial Release'
=> Fix typos in 'The Initial Release'

docs/articles/what-is-an-IoT-solution.md
Add reference to Clemens Vasters' Service Assisted Communication principle
=> Add reference to Service Assisted Communication

provision/README.md
Clarified a couple of issues users will run the provisioning scripts
with allot less issues.
=> updated readme for provisioning

src/Implementation/WarmStorage/WarmStorage/ElasticSearchWriter/ElasticSearchWriter.cs, src/Implementation/WarmStorage/WarmStorage/WarmStorageCoordinator.cs, src/RunFromConsole/mysettings-template.config
=> Fixed error while trying to serialize empty messages.

provision/Provision-All.ps1
=> Updated scripts to include WarmStorage configuration.

provision/Provision-All.ps1, provision/Provision-StreamAnalyticsJob.ps1
=> Implemented upload of reference data.

src/Implementation/Simulator/ScenarioSimulator/SimulatorConfiguration.cs, src/RunFromConsole/ScenarioSimulator.ConsoleHost/Program.cs, src/RunFromConsole/mysettings-template.config
=> Made log level configurable.

docs/challenges-and-questions.md
@mikewasson can you take a look at this?
=> Adding a list of challenges

docs/articles/introduction-to-IoT-security.md
Changed some small typos to make the document more fluently.
=> Small typo fixes

src/Implementation/ColdStorage/ColdStorage/ColdStorageCoordinator.cs, src/Implementation/ColdStorage/ColdStorage/ColdStorageProcessor.cs, src/Implementation/ColdStorage/ColdStorage/RollingBlobWriter/RollingBlobWriter.cs, src/Implementation/Shared/Tests.Common/Helpers/AzureStorageHelpers.cs, src/Implementation/Simulator/ScenarioSimulator/Device.cs, src/Implementation/Simulator/ScenarioSimulator/EventSender.cs, src/Implementation/Simulator/ScenarioSimulator/SimulationProfile.cs, src/RunFromConsole/ScenarioSimulator.ConsoleHost/Program.cs, src/RunFromConsole/WarmStorage.ConsoleHost/Program.cs
Connects to #171 
This is to close off the bug #171.   Have rerun the code to validate that we are getting devices are running on separate threads instead of the main thread.
=> Added ConfigureWait(false) to await methods calls

src/Simulator/ScenarioSimulator.ConsoleHost/ScenarioSimulator.ConsoleHost.csproj, src/Simulator/ScenarioSimulator/SimulatorConfiguration.cs
There were a couple of minor errors .
=> Fixing some simulator configuration problems

src/Simulator/ScenarioSimulator/SimulationProfile.cs
=> Spreading the warm up time over the number of devices

setup/Provision-ColdStorageEventProcessor.ps1, setup/Provision-WarmStorageEventProcessor.ps1
=> update script to copy template.cofig files

docs/articles/security-challenges.md
=> Add doc on security challenges

docs/01-what-is-an-IoT-solution.md, docs/02-architecting-IoT-solutions.md, docs/03-reference-implementation.md
=> Edit pass for content

setup/Provision-WarmStorageEventProcessor.ps1
=> Updated scripts for elasticsearch worker role.

src/IoTJourney.ruleset, src/Shared/Core/Core.csproj, src/Shared/Devices.Events/Devices.Events.csproj, src/Simulator/ScenarioSimulator.ConsoleHost/ScenarioSimulator.ConsoleHost.csproj, src/Simulator/ScenarioSimulator.WorkerRole/ScenarioSimulator.WorkerRole.csproj, src/Simulator/ScenarioSimulator/ScenarioSimulator.csproj, src/Simulator/nuget.config
=> fixes static analysis issues.

setup/modules/AzureARM.psm1, setup/modules/AzureSqlDatabase.psm1
- Now we are creating standard edition databases by default. 
- Fixed issue with connection.Open() in Invoke-Sql commandlet.
connects to #229
=> SQL Web DB we provision are being sunset Sept 2015
